FROM golang:1.19.0-bullseye AS build
ARG VERSION="local"
COPY . /app
WORKDIR /app
RUN go get -d
RUN useradd -u 10001 scratchuser
RUN go test -test.timeout 30s 
RUN CGO_ENABLED=0 go build -o scuttle -ldflags="-X 'main.Version=${VERSION}'"

FROM scratch
USER scratchuser
COPY --from=0 /etc/passwd /etc/passwd
COPY --from=build /app/scuttle /scuttle
