name: Main

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.14.x'

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go version
          go test -test.timeout 30s
          GOOS=linux GOARCH=amd64 go build -o build/linux/amd64/scuttle

      ################################################
      # Create Github release if this is a tag push
      - name: Pack
        run: |
          mkdir build/artifacts 
          zip -r -j build/artifacts/scuttle-linux-amd64.zip build/linux/amd64/
        if: startsWith(github.ref, 'refs/tags/')
     
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
